name: CI/CD with Terraform Control

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd project-1-app
          docker build -t abderahim7875/devops-app:latest .

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push abderahim7875/devops-app:latest

  terraform-apply:
    if: github.event.inputs.action == 'apply' || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd projet-3-terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd projet-3-terraform
          terraform apply -auto-approve

  terraform-destroy:
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd projet-3-terraform
          terraform init

      - name: Terraform Destroy
        run: |
          cd projet-3-terraform
          terraform destroy -auto-approve     
